INSERT INTO BRAND(BRANDID, BRANDNAME, STOREID) VALUES (1,'Swanson', 1);
INSERT INTO BRAND(BRANDID, BRANDNAME, STOREID) VALUES (2,'Nature Made', 2);
INSERT INTO BRAND(BRANDID, BRANDNAME, STOREID) VALUES (3,'CVS', 5);
INSERT INTO BRAND(BRANDID, BRANDNAME, STOREID) VALUES (4,'Walmart', 4);