INSERT INTO VITAMINS(VITAMINID, NAME, BENEFITS, DOSAGE, BRANDID) VALUES (1,'A','Vision, Immunity','300mg', 1);
INSERT INTO VITAMINS(VITAMINID, NAME, BENEFITS, DOSAGE, BRANDID) VALUES (2,'B1','Metabolism, Energy','100mg', 2);
INSERT INTO VITAMINS(VITAMINID, NAME, BENEFITS, DOSAGE, BRANDID) VALUES (3,'B2','Metabolism, Energy','100mg', 3);
INSERT INTO VITAMINS(VITAMINID, NAME, BENEFITS, DOSAGE, BRANDID) VALUES (4,'B12','DNA','200mg', 1);
INSERT INTO VITAMINS(VITAMINID, NAME, BENEFITS, DOSAGE, BRANDID) VALUES (5,'C','Energy','1000mg', 2);
INSERT INTO VITAMINS(VITAMINID, NAME, BENEFITS, DOSAGE, BRANDID) VALUES (6,'D','Multiple','5000ui', 2);
INSERT INTO VITAMINS(VITAMINID, NAME, BENEFITS, DOSAGE, BRANDID) VALUES (7,'E','Vision','200mg', 4);
INSERT INTO VITAMINS(VITAMINID, NAME, BENEFITS, DOSAGE, BRANDID) VALUES (8,'K','Blood Clotting','300mg', 1);