INSERT INTO VITAMINSTORE(STOREID, STORENAME, LOCATION) VALUES (1,'GNC','Albany, NY');
INSERT INTO VITAMINSTORE(STOREID, STORENAME, LOCATION) VALUES (2,'Vitamin Shoppe','Troy, NY');
INSERT INTO VITAMINSTORE(STOREID, STORENAME, LOCATION) VALUES (3,'Walmart','Saratoga, NY');
INSERT INTO VITAMINSTORE(STOREID, STORENAME, LOCATION) VALUES (4,'CVS','Albany, NY');
INSERT INTO VITAMINSTORE(STOREID, STORENAME, LOCATION) VALUES (5,'Walgreens','Albany, NY');